### ISSUE TITLE
LogisticGAM sample() function fails due to shape mismatch

### ISSUE THREAD

**Issue by daniel-s-cunha** [dswah/pyGAM#257]
>>> samples = gam1.sample(X_dontV, y1, quantity='mu',n_draws=1000, n_bootstraps=5, objective='auto')
100% (11 of 11) |##################################################################################################################################################| Elapsed Time: 0:00:01 Time:  0:00:01
100% (11 of 11) |##################################################################################################################################################| Elapsed Time: 0:00:01 Time:  0:00:01
100% (11 of 11) |##################################################################################################################################################| Elapsed Time: 0:00:01 Time:  0:00:01
100% (11 of 11) |##################################################################################################################################################| Elapsed Time: 0:00:01 Time:  0:00:01

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/anaconda3/lib/python3.6/site-packages/pygam/pygam.py", line 2030, in sample
    n_bootstraps=n_bootstraps, objective=objective)
  File "/anaconda3/lib/python3.6/site-packages/pygam/pygam.py", line 2108, in _sample_coef
    n_draws, coef_bootstraps, cov_bootstraps)
  File "/anaconda3/lib/python3.6/site-packages/pygam/pygam.py", line 2189, in _simulate_coef_from_bootstraps
    size=len(draw_indices))
ValueError: shape mismatch: value array of shape (204,51) could not be broadcast to indexing result of shape (204,52)

**Comment by Mudassiruddin7** [comment]
This turned out to be a downstream effect of the LogitLink overflow bug (#367). When LogitLink.mu() overflowed, mu contained inf, and BinomialDist.sample() couldn't handle that, causing the shape mismatch. for #367 keeps mu in [0, 1] throughout, so sampling works. Tested directly.
