### ISSUE TITLE
Overflow RuntimeWarning

### ISSUE THREAD

**Issue by ouslan** [dswah/pyGAM#367]
There seems to be some overflow in line 197  in `pygam/links.py`. This is mostly cause by exceeding the float value. The easiest fix would be to clip the function with `np.clip` to a smaller value like 700 to prevent this overflow. I manage to fix it but will open the PR after   #366 has been merge to main.

**Comment by cabreraalex** [comment]
I got something similar at a different spot:

```python
FloatingPointError: overflow encountered in square
2025-08-07 21:19:47 - forward_feature_selection - WARNING - [forward_feature_selection.py:155] - CV run 0 failed: overflow encountered in square
Traceback (most recent call last):
  File "/pkg/modal/_runtime/container_io_manager.py", line 772, in handle_input_exception
    yield
  File "/pkg/modal/_container_entrypoint.py", line 236, in run_input_sync
    res = io_context.call_finalized_function()
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/pkg/modal/_runtime/container_io_manager.py", line 194, in call_finalized_function
    res = self.finalized_function.callable(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/forward_feature_selection.py", line 194, in run_forward_selection_modal
    raise RuntimeError("Baseline model training failed")
RuntimeError: Baseline model training failed
```

**Comment by dswah** [comment]
OK this is a good idea.
i think we may want to add a tiny value to the denominators, and clip values before exponentiation (on values greater than 1)?

**Comment by Pratham-ja** [comment]
Hi @dswah,
I’ve raised a PR to address this issue by clipping the values to prevent the overflow problem. I’ve also added corresponding test cases to cover the changes.
Could you please take a look? [(https://github.com/dswah/pyGAM/pull/438)]

Thanks!

**Comment by kushvinth** [comment]
Hello @cabreraalex @dswah @ouslan @Pratham-ja @jonathan-taylor,
This issue is fixed at #447.

CI/CD Passes Unlike the other PRs

**Comment by Mudassiruddin7** [comment]
The overflow in LogitLink.mu() was coming from np.exp(lp) with no bounds — any linear predictor above ~709 overflows to inf. Switched to scipy.special.expit() which handles this correctly. Same class of problem in LogLink.mu(), fixed with clipping. Also guarded LogitLink.gradient() against division by zero at boundaries, and clamped the product in _W() to eps minimum before the power.
